/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ProtectedIndexRouteImport } from './routes/_protected/index'
import { Route as ProtectedConfirmTripRouteImport } from './routes/_protected/confirm-trip'
import { Route as ProtectedProtectedRouteRouteImport } from './routes/_protected/_protectedRoute'
import { Route as ProtectedTripsTripIdRouteImport } from './routes/_protected/trips/$tripId'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedIndexRoute = ProtectedIndexRouteImport.update({
  id: '/_protected/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedConfirmTripRoute = ProtectedConfirmTripRouteImport.update({
  id: '/_protected/confirm-trip',
  path: '/confirm-trip',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedProtectedRouteRoute = ProtectedProtectedRouteRouteImport.update({
  id: '/_protected/_protectedRoute',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedTripsTripIdRoute = ProtectedTripsTripIdRouteImport.update({
  id: '/_protected/trips/$tripId',
  path: '/trips/$tripId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/confirm-trip': typeof ProtectedConfirmTripRoute
  '/': typeof ProtectedIndexRoute
  '/trips/$tripId': typeof ProtectedTripsTripIdRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/confirm-trip': typeof ProtectedConfirmTripRoute
  '/': typeof ProtectedIndexRoute
  '/trips/$tripId': typeof ProtectedTripsTripIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/_protected/_protectedRoute': typeof ProtectedProtectedRouteRoute
  '/_protected/confirm-trip': typeof ProtectedConfirmTripRoute
  '/_protected/': typeof ProtectedIndexRoute
  '/_protected/trips/$tripId': typeof ProtectedTripsTripIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/login' | '/register' | '/confirm-trip' | '/' | '/trips/$tripId'
  fileRoutesByTo: FileRoutesByTo
  to: '/login' | '/register' | '/confirm-trip' | '/' | '/trips/$tripId'
  id:
    | '__root__'
    | '/login'
    | '/register'
    | '/_protected/_protectedRoute'
    | '/_protected/confirm-trip'
    | '/_protected/'
    | '/_protected/trips/$tripId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  ProtectedProtectedRouteRoute: typeof ProtectedProtectedRouteRoute
  ProtectedConfirmTripRoute: typeof ProtectedConfirmTripRoute
  ProtectedIndexRoute: typeof ProtectedIndexRoute
  ProtectedTripsTripIdRoute: typeof ProtectedTripsTripIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/': {
      id: '/_protected/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof ProtectedIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/confirm-trip': {
      id: '/_protected/confirm-trip'
      path: '/confirm-trip'
      fullPath: '/confirm-trip'
      preLoaderRoute: typeof ProtectedConfirmTripRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/_protectedRoute': {
      id: '/_protected/_protectedRoute'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof ProtectedProtectedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/trips/$tripId': {
      id: '/_protected/trips/$tripId'
      path: '/trips/$tripId'
      fullPath: '/trips/$tripId'
      preLoaderRoute: typeof ProtectedTripsTripIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  ProtectedProtectedRouteRoute: ProtectedProtectedRouteRoute,
  ProtectedConfirmTripRoute: ProtectedConfirmTripRoute,
  ProtectedIndexRoute: ProtectedIndexRoute,
  ProtectedTripsTripIdRoute: ProtectedTripsTripIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
