/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as ProfilRouteImport } from './routes/profil'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ConfirmTripRouteImport } from './routes/confirm-trip'
import { Route as ProtectedRouteImport } from './routes/_protected'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TripsTripIdRouteImport } from './routes/trips/$tripId'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfilRoute = ProfilRouteImport.update({
  id: '/profil',
  path: '/profil',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfirmTripRoute = ConfirmTripRouteImport.update({
  id: '/confirm-trip',
  path: '/confirm-trip',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedRoute = ProtectedRouteImport.update({
  id: '/_protected',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TripsTripIdRoute = TripsTripIdRouteImport.update({
  id: '/trips/$tripId',
  path: '/trips/$tripId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/confirm-trip': typeof ConfirmTripRoute
  '/login': typeof LoginRoute
  '/profil': typeof ProfilRoute
  '/register': typeof RegisterRoute
  '/trips/$tripId': typeof TripsTripIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/confirm-trip': typeof ConfirmTripRoute
  '/login': typeof LoginRoute
  '/profil': typeof ProfilRoute
  '/register': typeof RegisterRoute
  '/trips/$tripId': typeof TripsTripIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_protected': typeof ProtectedRoute
  '/confirm-trip': typeof ConfirmTripRoute
  '/login': typeof LoginRoute
  '/profil': typeof ProfilRoute
  '/register': typeof RegisterRoute
  '/trips/$tripId': typeof TripsTripIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/confirm-trip'
    | '/login'
    | '/profil'
    | '/register'
    | '/trips/$tripId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/confirm-trip'
    | '/login'
    | '/profil'
    | '/register'
    | '/trips/$tripId'
  id:
    | '__root__'
    | '/'
    | '/_protected'
    | '/confirm-trip'
    | '/login'
    | '/profil'
    | '/register'
    | '/trips/$tripId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProtectedRoute: typeof ProtectedRoute
  ConfirmTripRoute: typeof ConfirmTripRoute
  LoginRoute: typeof LoginRoute
  ProfilRoute: typeof ProfilRoute
  RegisterRoute: typeof RegisterRoute
  TripsTripIdRoute: typeof TripsTripIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profil': {
      id: '/profil'
      path: '/profil'
      fullPath: '/profil'
      preLoaderRoute: typeof ProfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/confirm-trip': {
      id: '/confirm-trip'
      path: '/confirm-trip'
      fullPath: '/confirm-trip'
      preLoaderRoute: typeof ConfirmTripRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected': {
      id: '/_protected'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof ProtectedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trips/$tripId': {
      id: '/trips/$tripId'
      path: '/trips/$tripId'
      fullPath: '/trips/$tripId'
      preLoaderRoute: typeof TripsTripIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProtectedRoute: ProtectedRoute,
  ConfirmTripRoute: ConfirmTripRoute,
  LoginRoute: LoginRoute,
  ProfilRoute: ProfilRoute,
  RegisterRoute: RegisterRoute,
  TripsTripIdRoute: TripsTripIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
